import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <div className='container mt-40 h-full'>
          <div className='mx-auto w-fit h-10'>
            {' '}
            <Link href={'/sign-up'}>
              <button className='bg-yellow-700 	text-white	px-8 py-4'>Sign Up</button>
            </Link>
          </div>
          <div className='mx-auto w-fit h-10 mt-20'>
            <Link href={'/sign-in'}>
              <button className='bg-yellow-700 	text-white	px-8 py-4 '>Sign In</button>
            </Link>
          </div>
        </div>
      </main>
    </>
  )
}
